AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  version-service

  SAM Template for version-service

Parameters:
  Stage:
    Type: String
  StageName:
    Type: String
  

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30    
    MemorySize: 256

    Environment:
      Variables:
        Stage: !Ref Stage
        RtRegion: !Sub ${AWS::Region}
        StageName: !Ref StageName
        UserConnectedTopicArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:Splitsies-UserConnected-${StageName}

    LoggingConfig:
      LogFormat: JSON

Resources:
  VersionServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: VersionServiceLambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Permissions to create and manage logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

              # Allow Lambda to publish SNS messages
              - Effect: Allow
                Action: sns:Publish
                Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:Splitsies-UserConnected-${StageName} 

  GetMinSupportedVersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handler.main
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Notify:
          Type: Api
          Properties:
            Path: /minimum
            Method: get
            RestApiId: !Ref VersionServiceApi
    Metadata: # Manage esbuild properties
        BuildMethod: esbuild
        BuildProperties:
          Minify: true
          Target: es2020
          Sourcemap: true
          EntryPoints:
          - functions/get-min-supported-version/handler.ts
          External:
          - node_modules
          - aws-sdk
          - esbuild

  GetProductionVersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handler.main
      Runtime: nodejs18.x
      Events:
        Notify:
          Type: Api
          Properties:
            Path: /stable
            Method: get
            RestApiId: !Ref VersionServiceApi
    Metadata: # Manage esbuild properties
        BuildMethod: esbuild
        BuildProperties:
          Minify: true
          Target: es2020
          Sourcemap: true
          EntryPoints:
          - functions/get-production-version/handler.ts
          External:
          - node_modules
          - aws-sdk
          - esbuild