AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  version-service

  SAM Template for version-service

Parameters:
  Stage:
    Type: String

Resources:
  # S3 Bucket for Content
  VersionConfigurationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "splitsies-${AWS::StackName}-${Stage}-bucket"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  # CloudFront Origin Access Identity (OAI) to restrict access to S3 bucket
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${AWS::StackName} to restrict S3 access"

  # S3 Bucket Policy to allow CloudFront to read content from S3
  S3VersionConfigurationBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref VersionConfigurationBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${VersionConfigurationBucket}/*"

  # CloudFront Distribution
  VersionCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: MyS3Origin
            DomainName: !GetAtt VersionConfigurationBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: MyS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
          DefaultTTL: 604800  # 1 week
          MaxTTL: 31536000  # 1 year
          MinTTL: 604800      # 1 week
        ViewerCertificate:
          CloudFrontDefaultCertificate: true  # Use default SSL certificate
        PriceClass: PriceClass_100  # For US/Europe only

Outputs:
  S3BucketName:
    Description: Version Configuration Bucket
    Value: !Ref VersionConfigurationBucket

  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt VersionCloudFrontDistribution.DomainName